"""
Pattern Comment Generator - Generates intelligent GitHub comments for pattern violations.

This module creates detailed, actionable comments that explain:
- What pattern was violated
- Why it matters (with evidence from legacy code)
- How to fix it (with code examples)
"""

import logging
from typing import List, Dict
from dataclasses import dataclass

from app.core.design_patterns.pattern_comparator import PatternViolation

logger = logging.getLogger(__name__)


@dataclass
class GitHubComment:
    """Represents a GitHub comment to be posted."""
    file_path: str
    line_number: int
    body: str
    severity: str


class PatternCommentGenerator:
    """Generates comments for pattern violations."""
    
    SEVERITY_EMOJIS = {
        "critical": "🚨",
        "high": "⚠️",
        "medium": "ℹ️",
        "low": "💡",
    }
    
    def generate_comments(
        self,
        violations: List[PatternViolation],
    ) -> List[GitHubComment]:
        """
        Generate GitHub comments for all violations.
        
        Args:
            violations: List of pattern violations
        
        Returns:
            List of GitHub comments
        """
        logger.info(f"Generating comments for {len(violations)} violations")
        
        comments = []
        
        for violation in violations:
            comment = self._generate_single_comment(violation)
            comments.append(comment)
        
        return comments
    
    def _generate_single_comment(
        self,
        violation: PatternViolation,
    ) -> GitHubComment:
        """Generate a single comment for a violation."""
        emoji = self.SEVERITY_EMOJIS.get(violation.severity, "")
        
        # Build comment body
        body_parts = []
        
        # Title
        body_parts.append(f"## {emoji} {violation.title}")
        body_parts.append("")
        
        # Severity
        body_parts.append(f"**Severity:** `{violation.severity.upper()}`")
        body_parts.append("")
        
        # Description
        body_parts.append(f"### Description")
        body_parts.append(violation.description)
        body_parts.append("")
        
        # Pattern context
        body_parts.append(f"### Pattern: {violation.pattern.name}")
        body_parts.append(violation.pattern.description)
        body_parts.append("")
        
        # Evidence from legacy code
        if violation.evidence:
            body_parts.append("### Evidence from existing codebase")
            body_parts.append("")
            body_parts.append(f"This pattern is used **{violation.pattern.occurrences} times** in the codebase:")
            body_parts.append("")
            for evidence in violation.evidence:
                body_parts.append(f"- {evidence}")
            body_parts.append("")
        
        # Expected vs Actual
        body_parts.append("### Expected vs Actual")
        body_parts.append("")
        body_parts.append("**Expected behavior:**")
        body_parts.append(f"```\n{violation.expected_behavior}\n```")
        body_parts.append("")
        body_parts.append("**Actual behavior:**")
        body_parts.append(f"```\n{violation.actual_behavior}\n```")
        body_parts.append("")
        
        # Code snippet if available
        if violation.diff_snippet:
            body_parts.append("### Code snippet")
            body_parts.append("```diff")
            body_parts.append(violation.diff_snippet)
            body_parts.append("```")
            body_parts.append("")
        
        # Recommendation
        body_parts.append("### 💡 Recommendation")
        body_parts.append(violation.recommendation)
        body_parts.append("")
        
        # Impact
        impact_percentage = int(violation.score_impact * 100)
        body_parts.append(f"**Pattern adherence impact:** {impact_percentage}% violation")
        body_parts.append("")
        
        # Footer
        body_parts.append("---")
        body_parts.append("*This finding was generated by Devora GraphRAG analysis*")
        
        return GitHubComment(
            file_path=violation.file_path,
            line_number=violation.line_number,
            body="\n".join(body_parts),
            severity=violation.severity,
        )
    
    def generate_summary_comment(
        self,
        violations: List[PatternViolation],
        patterns_analyzed: List[str],
    ) -> str:
        """
        Generate a summary comment for the entire PR.
        
        Args:
            violations: All violations found
            patterns_analyzed: List of pattern names that were checked
        
        Returns:
            Summary comment body
        """
        body_parts = []
        
        # Title
        body_parts.append("# 🔍 Devora Design Pattern Analysis")
        body_parts.append("")
        
        # Stats
        total_violations = len(violations)
        critical = len([v for v in violations if v.severity == "critical"])
        high = len([v for v in violations if v.severity == "high"])
        medium = len([v for v in violations if v.severity == "medium"])
        low = len([v for v in violations if v.severity == "low"])
        
        body_parts.append("## Summary")
        body_parts.append("")
        body_parts.append(f"**Total pattern violations:** {total_violations}")
        body_parts.append("")
        body_parts.append(f"- 🚨 Critical: {critical}")
        body_parts.append(f"- ⚠️  High: {high}")
        body_parts.append(f"- ℹ️  Medium: {medium}")
        body_parts.append(f"- 💡 Low: {low}")
        body_parts.append("")
        
        # Patterns checked
        body_parts.append("## Patterns Analyzed")
        body_parts.append("")
        for pattern_name in patterns_analyzed:
            body_parts.append(f"- ✅ {pattern_name}")
        body_parts.append("")
        
        # Violations by pattern
        if violations:
            body_parts.append("## Violations by Pattern")
            body_parts.append("")
            
            violations_by_pattern = {}
            for v in violations:
                pattern_name = v.pattern.name
                if pattern_name not in violations_by_pattern:
                    violations_by_pattern[pattern_name] = []
                violations_by_pattern[pattern_name].append(v)
            
            for pattern_name, pattern_violations in violations_by_pattern.items():
                body_parts.append(f"### {pattern_name}")
                body_parts.append(f"Found {len(pattern_violations)} violation(s):")
                body_parts.append("")
                
                for v in pattern_violations[:3]:  # Show top 3
                    emoji = self.SEVERITY_EMOJIS.get(v.severity, "")
                    body_parts.append(f"- {emoji} **{v.title}** ({v.file_path}:{v.line_number})")
                
                if len(pattern_violations) > 3:
                    body_parts.append(f"- ... and {len(pattern_violations) - 3} more")
                
                body_parts.append("")
        
        # Recommendations
        body_parts.append("## 💡 Next Steps")
        body_parts.append("")
        
        if critical > 0:
            body_parts.append("⚠️  **Critical violations must be fixed before merging.**")
            body_parts.append("")
        
        if high > 0:
            body_parts.append("High-severity violations should be addressed to maintain code quality.")
            body_parts.append("")
        
        body_parts.append("Review the inline comments for detailed recommendations.")
        body_parts.append("")
        
        # Footer
        body_parts.append("---")
        body_parts.append("*Analysis powered by Devora GraphRAG - Pattern detection from legacy codebase*")
        
        return "\n".join(body_parts)
    
    def generate_comparison_comment(
        self,
        pattern_name: str,
        legacy_example: str,
        pr_example: str,
    ) -> str:
        """
        Generate a side-by-side comparison comment.
        
        Args:
            pattern_name: Name of the pattern
            legacy_example: Code from legacy codebase
            pr_example: Code from PR
        
        Returns:
            Comparison comment
        """
        body_parts = []
        
        body_parts.append(f"## Pattern Comparison: {pattern_name}")
        body_parts.append("")
        body_parts.append("### ✅ Legacy code (follows pattern)")
        body_parts.append("```javascript")
        body_parts.append(legacy_example)
        body_parts.append("```")
        body_parts.append("")
        body_parts.append("### ❌ PR code (violates pattern)")
        body_parts.append("```javascript")
        body_parts.append(pr_example)
        body_parts.append("```")
        body_parts.append("")
        body_parts.append("**Recommendation:** Update PR code to follow the established pattern.")
        
        return "\n".join(body_parts)
