"""Project Profile dataclasses for comprehensive project understanding.

These dataclasses represent the complete profile of a repository including
structure, architecture, quality indicators, and human-readable descriptions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class ArchitecturePattern(str, Enum):
    """Detected architecture patterns."""

    MONOLITH = "monolith"
    MICROSERVICES = "microservices"
    SERVERLESS = "serverless"
    MODULAR_MONOLITH = "modular_monolith"
    LAYERED = "layered"
    HEXAGONAL = "hexagonal"
    EVENT_DRIVEN = "event_driven"
    UNKNOWN = "unknown"


class PackageManager(str, Enum):
    """Supported package managers."""

    NPM = "npm"
    YARN = "yarn"
    PNPM = "pnpm"
    PIP = "pip"
    POETRY = "poetry"
    PIPENV = "pipenv"
    UV = "uv"
    CARGO = "cargo"
    GO_MOD = "go_mod"
    MAVEN = "maven"
    GRADLE = "gradle"
    COMPOSER = "composer"
    BUNDLER = "bundler"
    NUGET = "nuget"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class StructureInfo:
    """Project structure information."""

    root_directories: tuple[str, ...]
    main_languages: tuple[str, ...]
    secondary_languages: tuple[str, ...]
    frameworks_detected: tuple[str, ...]
    package_managers: tuple[PackageManager, ...]
    total_files: int
    total_directories: int
    code_files_count: int
    config_files_count: int
    doc_files_count: int
    test_files_count: int


@dataclass(frozen=True)
class ArchitectureInfo:
    """Project architecture information."""

    pattern: ArchitecturePattern
    pattern_confidence: float
    entry_points: tuple[str, ...]
    core_modules: tuple[str, ...]
    api_endpoints_count: int
    has_api_layer: bool
    has_data_layer: bool
    has_service_layer: bool
    has_presentation_layer: bool
    layer_separation_score: float  # 0-1, how well separated are the layers


@dataclass(frozen=True)
class QualityIndicators:
    """Project quality indicators."""

    has_tests: bool
    test_framework: str | None
    test_coverage_estimated: float | None  # 0-1, estimated based on test file ratio
    has_ci_cd: bool
    ci_cd_platform: str | None  # github_actions, gitlab_ci, jenkins, etc.
    has_documentation: bool
    documentation_quality_score: float  # 0-1
    has_readme: bool
    has_contributing: bool
    has_license: bool
    has_changelog: bool
    has_linting: bool
    linting_tools: tuple[str, ...]
    has_type_hints: bool  # For Python/TypeScript
    type_coverage_estimated: float | None


@dataclass(frozen=True)
class DependencyInfo:
    """Project dependency information."""

    external_dependencies: tuple[str, ...]
    external_dependencies_count: int
    dev_dependencies_count: int
    internal_modules: tuple[str, ...]
    internal_dependencies_graph: dict[str, tuple[str, ...]]  # module -> [imports]
    has_lockfile: bool
    outdated_dependencies_count: int | None
    security_vulnerabilities_count: int | None


@dataclass
class ProjectProfile:
    """Comprehensive project profile for repository understanding.

    This is the main dataclass that contains all extracted information about
    a repository. It is used to:
    1. Store in Qdrant for semantic search
    2. Store in PostgreSQL for quick retrieval
    3. Generate human-readable descriptions for the frontend
    4. Provide context for RAG-based code review
    """

    # Identifiers
    repo_id: str
    org_id: str | None = None
    context_version: int = 1

    # Structure Information
    structure: StructureInfo | None = None

    # Architecture Information
    architecture: ArchitectureInfo | None = None

    # Quality Indicators
    quality: QualityIndicators | None = None

    # Dependencies
    dependencies: DependencyInfo | None = None

    # Descriptions (generated by LLM)
    business_description: str | None = None  # Non-technical, for UI display
    technical_summary: str | None = None  # Technical overview

    # Raw extracted data for advanced queries
    raw_metadata: dict[str, Any] = field(default_factory=dict)

    # Timestamps
    created_at: datetime | None = None
    last_analyzed_at: datetime | None = None
    last_context_update_at: datetime | None = None

    # Status
    analysis_status: str = "pending"  # pending, analyzing, completed, failed
    analysis_error: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert profile to dictionary for storage."""
        return {
            "repo_id": self.repo_id,
            "org_id": self.org_id,
            "context_version": self.context_version,
            "structure": self._structure_to_dict() if self.structure else None,
            "architecture": self._architecture_to_dict() if self.architecture else None,
            "quality": self._quality_to_dict() if self.quality else None,
            "dependencies": self._dependencies_to_dict() if self.dependencies else None,
            "business_description": self.business_description,
            "technical_summary": self.technical_summary,
            "raw_metadata": self.raw_metadata,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "last_analyzed_at": self.last_analyzed_at.isoformat() if self.last_analyzed_at else None,
            "last_context_update_at": self.last_context_update_at.isoformat() if self.last_context_update_at else None,
            "analysis_status": self.analysis_status,
            "analysis_error": self.analysis_error,
        }

    def _structure_to_dict(self) -> dict[str, Any]:
        if not self.structure:
            return {}
        return {
            "root_directories": list(self.structure.root_directories),
            "main_languages": list(self.structure.main_languages),
            "secondary_languages": list(self.structure.secondary_languages),
            "frameworks_detected": list(self.structure.frameworks_detected),
            "package_managers": [pm.value for pm in self.structure.package_managers],
            "total_files": self.structure.total_files,
            "total_directories": self.structure.total_directories,
            "code_files_count": self.structure.code_files_count,
            "config_files_count": self.structure.config_files_count,
            "doc_files_count": self.structure.doc_files_count,
            "test_files_count": self.structure.test_files_count,
        }

    def _architecture_to_dict(self) -> dict[str, Any]:
        if not self.architecture:
            return {}
        return {
            "pattern": self.architecture.pattern.value,
            "pattern_confidence": self.architecture.pattern_confidence,
            "entry_points": list(self.architecture.entry_points),
            "core_modules": list(self.architecture.core_modules),
            "api_endpoints_count": self.architecture.api_endpoints_count,
            "has_api_layer": self.architecture.has_api_layer,
            "has_data_layer": self.architecture.has_data_layer,
            "has_service_layer": self.architecture.has_service_layer,
            "has_presentation_layer": self.architecture.has_presentation_layer,
            "layer_separation_score": self.architecture.layer_separation_score,
        }

    def _quality_to_dict(self) -> dict[str, Any]:
        if not self.quality:
            return {}
        return {
            "has_tests": self.quality.has_tests,
            "test_framework": self.quality.test_framework,
            "test_coverage_estimated": self.quality.test_coverage_estimated,
            "has_ci_cd": self.quality.has_ci_cd,
            "ci_cd_platform": self.quality.ci_cd_platform,
            "has_documentation": self.quality.has_documentation,
            "documentation_quality_score": self.quality.documentation_quality_score,
            "has_readme": self.quality.has_readme,
            "has_contributing": self.quality.has_contributing,
            "has_license": self.quality.has_license,
            "has_changelog": self.quality.has_changelog,
            "has_linting": self.quality.has_linting,
            "linting_tools": list(self.quality.linting_tools),
            "has_type_hints": self.quality.has_type_hints,
            "type_coverage_estimated": self.quality.type_coverage_estimated,
        }

    def _dependencies_to_dict(self) -> dict[str, Any]:
        if not self.dependencies:
            return {}
        return {
            "external_dependencies": list(self.dependencies.external_dependencies),
            "external_dependencies_count": self.dependencies.external_dependencies_count,
            "dev_dependencies_count": self.dependencies.dev_dependencies_count,
            "internal_modules": list(self.dependencies.internal_modules),
            "internal_dependencies_graph": {
                k: list(v) for k, v in self.dependencies.internal_dependencies_graph.items()
            },
            "has_lockfile": self.dependencies.has_lockfile,
            "outdated_dependencies_count": self.dependencies.outdated_dependencies_count,
            "security_vulnerabilities_count": self.dependencies.security_vulnerabilities_count,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ProjectProfile:
        """Create ProjectProfile from dictionary."""
        profile = cls(
            repo_id=data["repo_id"],
            org_id=data.get("org_id"),
            context_version=data.get("context_version", 1),
            business_description=data.get("business_description"),
            technical_summary=data.get("technical_summary"),
            raw_metadata=data.get("raw_metadata", {}),
            analysis_status=data.get("analysis_status", "pending"),
            analysis_error=data.get("analysis_error"),
        )

        if data.get("structure"):
            profile.structure = cls._structure_from_dict(data["structure"])
        if data.get("architecture"):
            profile.architecture = cls._architecture_from_dict(data["architecture"])
        if data.get("quality"):
            profile.quality = cls._quality_from_dict(data["quality"])
        if data.get("dependencies"):
            profile.dependencies = cls._dependencies_from_dict(data["dependencies"])

        if data.get("created_at"):
            profile.created_at = datetime.fromisoformat(data["created_at"])
        if data.get("last_analyzed_at"):
            profile.last_analyzed_at = datetime.fromisoformat(data["last_analyzed_at"])
        if data.get("last_context_update_at"):
            profile.last_context_update_at = datetime.fromisoformat(data["last_context_update_at"])

        return profile

    @staticmethod
    def _structure_from_dict(data: dict[str, Any]) -> StructureInfo:
        return StructureInfo(
            root_directories=tuple(data.get("root_directories", [])),
            main_languages=tuple(data.get("main_languages", [])),
            secondary_languages=tuple(data.get("secondary_languages", [])),
            frameworks_detected=tuple(data.get("frameworks_detected", [])),
            package_managers=tuple(
                PackageManager(pm) if pm in [e.value for e in PackageManager] else PackageManager.UNKNOWN
                for pm in data.get("package_managers", [])
            ),
            total_files=data.get("total_files", 0),
            total_directories=data.get("total_directories", 0),
            code_files_count=data.get("code_files_count", 0),
            config_files_count=data.get("config_files_count", 0),
            doc_files_count=data.get("doc_files_count", 0),
            test_files_count=data.get("test_files_count", 0),
        )

    @staticmethod
    def _architecture_from_dict(data: dict[str, Any]) -> ArchitectureInfo:
        pattern_value = data.get("pattern", "unknown")
        pattern = (
            ArchitecturePattern(pattern_value)
            if pattern_value in [e.value for e in ArchitecturePattern]
            else ArchitecturePattern.UNKNOWN
        )
        return ArchitectureInfo(
            pattern=pattern,
            pattern_confidence=data.get("pattern_confidence", 0.0),
            entry_points=tuple(data.get("entry_points", [])),
            core_modules=tuple(data.get("core_modules", [])),
            api_endpoints_count=data.get("api_endpoints_count", 0),
            has_api_layer=data.get("has_api_layer", False),
            has_data_layer=data.get("has_data_layer", False),
            has_service_layer=data.get("has_service_layer", False),
            has_presentation_layer=data.get("has_presentation_layer", False),
            layer_separation_score=data.get("layer_separation_score", 0.0),
        )

    @staticmethod
    def _quality_from_dict(data: dict[str, Any]) -> QualityIndicators:
        return QualityIndicators(
            has_tests=data.get("has_tests", False),
            test_framework=data.get("test_framework"),
            test_coverage_estimated=data.get("test_coverage_estimated"),
            has_ci_cd=data.get("has_ci_cd", False),
            ci_cd_platform=data.get("ci_cd_platform"),
            has_documentation=data.get("has_documentation", False),
            documentation_quality_score=data.get("documentation_quality_score", 0.0),
            has_readme=data.get("has_readme", False),
            has_contributing=data.get("has_contributing", False),
            has_license=data.get("has_license", False),
            has_changelog=data.get("has_changelog", False),
            has_linting=data.get("has_linting", False),
            linting_tools=tuple(data.get("linting_tools", [])),
            has_type_hints=data.get("has_type_hints", False),
            type_coverage_estimated=data.get("type_coverage_estimated"),
        )

    @staticmethod
    def _dependencies_from_dict(data: dict[str, Any]) -> DependencyInfo:
        return DependencyInfo(
            external_dependencies=tuple(data.get("external_dependencies", [])),
            external_dependencies_count=data.get("external_dependencies_count", 0),
            dev_dependencies_count=data.get("dev_dependencies_count", 0),
            internal_modules=tuple(data.get("internal_modules", [])),
            internal_dependencies_graph={
                k: tuple(v) for k, v in data.get("internal_dependencies_graph", {}).items()
            },
            has_lockfile=data.get("has_lockfile", False),
            outdated_dependencies_count=data.get("outdated_dependencies_count"),
            security_vulnerabilities_count=data.get("security_vulnerabilities_count"),
        )

    def get_embedding_text(self) -> str:
        """Generate text representation for embedding."""
        parts = [
            f"repo:{self.repo_id}",
        ]

        if self.structure:
            parts.append(f"languages:{','.join(self.structure.main_languages)}")
            parts.append(f"frameworks:{','.join(self.structure.frameworks_detected)}")

        if self.architecture:
            parts.append(f"architecture:{self.architecture.pattern.value}")
            parts.append(f"modules:{','.join(self.architecture.core_modules[:10])}")

        if self.quality:
            quality_aspects = []
            if self.quality.has_tests:
                quality_aspects.append("tested")
            if self.quality.has_ci_cd:
                quality_aspects.append("ci_cd")
            if self.quality.has_documentation:
                quality_aspects.append("documented")
            if self.quality.has_type_hints:
                quality_aspects.append("typed")
            if quality_aspects:
                parts.append(f"quality:{','.join(quality_aspects)}")

        if self.business_description:
            parts.append(self.business_description)

        if self.technical_summary:
            parts.append(self.technical_summary)

        return "\n".join(parts)
